---
- name: Install Sublime Text (.deb) on Linux
  hosts: linux_servers
  become: yes

  vars:
    sublime_deb_url: "https://download.sublimetext.com/sublime-text_latest_amd64.deb"
    sublime_deb_file: "/tmp/sublime.deb"

  tasks:

    - name: Download Sublime .deb package
      get_url:
        url: "{{ sublime_deb_url }}"
        dest: "{{ sublime_deb_file }}"

    - name: Install Sublime Text package
      apt:
        deb: "{{ sublime_deb_file }}"
        state: present
